package io.penblog.filewizard.enums.options;

public enum Option {
    RENAME_NEW_NAME_TEXT,
    RENAME_APPEND_TEXT,
    RENAME_PREPEND_TEXT,

    RENAME_REPLACE_SEARCH,
    RENAME_REPLACE_TEXT,

    RENAME_REMOVE_CASE_INSENSITIVE,
    RENAME_REMOVE_REGEX,
    RENAME_REMOVE_TEXT,

    RENAME_SEQUENCE_TEXT,

    RENAME_LOWERCASE_OPTION,
    RENAME_LOWERCASE_SPECIFIC_CHARACTERS_TEXT,

    RENAME_UPPERCASE_OPTION,
    RENAME_UPPERCASE_SPECIFIC_CHARACTERS_TEXT,


    MOVE_NEW_NAME_TEXT,
    MOVE_SEQUENCE_TEXT,
}
